name = "actual_chocolate_wren-9335"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "actual_chocolate_wren-9335_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "actual_chocolate_wren-9335.wasm"
command = "npm run build:release"
